ajoberstar/grgit

src/main/groovy/org/ajoberstar/grgit/exception/GrgitException.groovy
Adding `@CompileStatic` here so you can compile subprojects that don't want dynamic methods on exceptions.  (for example when I compile https://github.com/ajoberstar/gradle-git)
=> adding CompileStatic to exception for strict compilers

README.md
After the click badge was shown instead of the page with details about the latest version.
It seems that I made that a partially broken PR some time ago ;).
=> Fix link to Maven Center badge

src/main/groovy/org/ajoberstar/grgit/Grgit.groovy, src/main/groovy/org/ajoberstar/grgit/operation/DescribeOp.groovy, src/test/groovy/org/ajoberstar/grgit/operation/DescribeOpSpec.groovy
it only functions on the current HEAD, but that's the biggest use case
the jgit describe command is very limited option wise compared to cgit, so there isn't that much that can be done without implementing it separately  
initial stab at #39
=> adding a very basic git describe command

src/test/groovy/org/ajoberstar/grgit/fixtures/MultiGitOpSpec.groovy
The problem occurred on Mac OS/X due to the way /var is mapped to /private/var.
Because of this mapping (it's a symbolic link) the "canonicalFile" method was returning /private/var in the test but /var was used in the test setup.  So, I added a call to "canonicalFile" in the test setup.  This problem may manifest itself on other platforms, too, so I believe this is the correct way to perform this test.
=> RemoteListOpSpec was failing, now it passes.

src/main/groovy/org/ajoberstar/grgit/operation/MergeOp.groovy
This is to fix #93.
All the current specs still pass. I first attempt to get a ref which results in the correct merge message. If a ref is not found (a partial sha would cause this), then I fall back to the old way of doing things which resolves the sha of the commit instead of a ref.
While I was looking at the code, I also noticed the jgit allows a message to be passed to the merge command so I went ahead and added that here as well. It has no tests though so if you want I can remove it from this PR.
=> Merge enhancements

src/main/groovy/org/ajoberstar/grgit/operation/BranchListOp.groovy, src/test/groovy/org/ajoberstar/grgit/operation/BranchListOpSpec.groovy
Hello. 
I implemented '--contains' param for branch list command.
=> Implement --contains flag for branch list

src/main/groovy/org/ajoberstar/grgit/auth/AuthConfig.groovy, src/main/groovy/org/ajoberstar/grgit/auth/JschAgentProxySessionFactory.groovy, src/test/groovy/org/ajoberstar/grgit/auth/AuthConfigSpec.groovy
Now someone could run it in this way:
```
./gradlew release -Dorg.ajoberstar.grgit.auth.ssh.private=~/.ssh/github_id_rsa \
-Dorg.ajoberstar.grgit.auth.session.config.StrictHostKeyChecking=no
```
=> Support more customization for ssh session, also disabling strict host key check #95

src/main/groovy/org/ajoberstar/grgit/operation/CloneOp.groovy, src/test/groovy/org/ajoberstar/grgit/operation/CloneOpSpec.groovy
The CloneCommand in JGit returns a reosurce that must be
closed in order to release a lock on the files in the repo.
This prevents someone from deleting a repo, even though they
close the Grgit instance.
Closing the resource has fixed #132.
=> Properly close resources in CloneOp

src/main/groovy/org/ajoberstar/grgit/auth/AuthConfig.groovy, src/main/groovy/org/ajoberstar/grgit/auth/JschAgentProxySessionFactory.groovy
When your repository is asking you a passphrase is could be painfull to have to give it for all your repo. You could enter it once when typing from your command line or when we create the grgit instance.
use -Dorg.ajoberstar.grgit.auth.passphrase=passphrase && -Dorg.ajoberstar.grgit.auth.force=hardcoded 
This will allow you tu use default ssl authentication + hardcoded passphrase usage
Please say if I have done a mistake or if my request should be improved in any way.
=> Add passphrase support for hardcoded authentication

src/main/groovy/org/ajoberstar/grgit/Credentials.groovy, src/main/groovy/org/ajoberstar/grgit/auth/AuthConfig.groovy, src/main/groovy/org/ajoberstar/grgit/auth/TransportOpUtil.groovy, src/test/groovy/org/ajoberstar/grgit/auth/AuthConfigSpec.groovy, src/test/groovy/org/ajoberstar/grgit/auth/LinuxAuthenticationSpec.groovy, src/test/groovy/org/ajoberstar/grgit/auth/WindowsAuthenticationSpec.groovy
Username-only creds are useful for things like GitHub access tokens.
Prior to this commit, specifying only a username resulted in a null
password, which caused an ambiguous method call to the
UserNamePasswordCredentialsProvider constructor.
Now Credentials has been beefed up to fallback to empty strings for
values that aren't provided. There's also an explicit method for how to
check the validity of a Credentials object rather than needing to
specify it directly in each case.
Fixes #153
=> Fix username-only creds

src/main/groovy/org/ajoberstar/grgit/operation/DescribeOp.groovy, src/test/groovy/org/ajoberstar/grgit/operation/DescribeOpSpec.groovy
Extension proposal: Make commit for describe operation configurable, using the [target configuration](https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/api/DescribeCommand.java#L82) provided by JGit.
=> Added a commit target to Describe operation.

src/main/groovy/org/ajoberstar/grgit/operation/DescribeOp.groovy, src/test/groovy/org/ajoberstar/grgit/operation/DescribeOpSpec.groovy
I currently patching the **grgit** in my `buildSrc` using the `metaClass`. 
In the end, it would be nice to transfer everything you consider to be fit and of common interests into grgit.
I think this one is still uncritical, so I provided it as a separated PR.
As you saw in my proposal for gradle-git, I still have some blind spots when it comes to GIT. Sorry that I was wasting your time.
=> Added --long option to Describe operation.

build.gradle, src/compatTest/groovy/org/ajoberstar/grgit/gradle/BaseCompatTest.groovy, src/main/groovy/org/ajoberstar/grgit/gradle/GrgitPlugin.groovy, src/main/groovy/org/ajoberstar/grgit/internal/OpSyntax.groovy, src/main/groovy/org/ajoberstar/grgit/internal/WithOperationsASTTransformation.java, src/main/resources/META-INF/gradle-plugins/org.ajoberstar.grgit.properties
This is being migrated from gradle-git. Differences from 1.7.x
gradle-git:
- Allow applying to projects besides the rootProject
- Warn if project was applied to root project and a subproject
- Add a close task that finalizes all other tasks
This resolves #178.
=> Adding org.ajoberstar.grgit Gradle plugin

src/main/groovy/org/ajoberstar/grgit/operation/LsRemoteOp.groovy
Credentials were not being configured on lsremote, unlike all other
TransportCommands that were being used.
This fixes #222.
=> Configure credentials on lsremote

src/main/groovy/org/ajoberstar/grgit/internal/WithOperationsASTTransformation.java, src/test/groovy/org/ajoberstar/grgit/operation/GenericOpTest.java
Incorrectly generating Consumer<Return> instead of Consumer<Op>. e.g.
for Grgit.commit() which returns a Commit, we generated Consumer<Commit>
instead of Consumer<CommitOp>. This now allows you to correctly use
Consumers as an option.
=> Generate correct Consumer type for ops

build.gradle, global.lock
The update defaults plugin has a fix for ensuring that POMs that go to
the plugin portal use static versions instead of ranges.
=> Publish static versions in plugin POM

build.gradle, global.lock
Unfortunately nebula-maven-resolved-dependencies doesn't seem to put
static versions into the POM of com.gradle-plugin-publish artifacts. It
does affect everything I'm pushing to Bintray though. So we've been
using super permissive dependency ranges out to everyone and now, people
are being bit by a breaking change in JGit 5.
This fixes for #229 to just make the JGit dependency static.
=> Use static JGit version

src/main/groovy/org/ajoberstar/grgit/operation/RevertOp.groovy, src/test/groovy/org/ajoberstar/grgit/operation/RevertOpSpec.groovy
When a JGit`RevertCommand` fails, then a null RevCommit is returned from the call method (see https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/api/RevertCommand.java#L219).
This PR adds a check for any failure modes and throws an exception (message shamelessly taken from `MergeOp`)
=> Fix issue when reverting a commit results in a failingResult

src/main/groovy/org/ajoberstar/grgit/Commit.groovy, src/main/groovy/org/ajoberstar/grgit/operation/CommitOp.groovy, src/main/groovy/org/ajoberstar/grgit/operation/LogOp.groovy, src/main/groovy/org/ajoberstar/grgit/operation/RevertOp.groovy, src/main/groovy/org/ajoberstar/grgit/util/JGitUtil.groovy, src/test/groovy/org/ajoberstar/grgit/operation/LogOpSpec.groovy, src/test/groovy/org/ajoberstar/grgit/util/JGitUtilSpec.groovy
JGit provides a method that ensures uniqueness. This is safer than the
old approach that just substringed. That option is still around, but
deprecated.
This fixes #238.
=> Ensure abbreviated commit IDs are unique

docs/content/grgit-open.adoc, grgit-core/src/main/groovy/org/ajoberstar/grgit/auth/TransportOpUtil.groovy, grgit-core/src/main/groovy/org/ajoberstar/grgit/operation/CloneOp.groovy, grgit-core/src/main/groovy/org/ajoberstar/grgit/operation/OpenOp.groovy, grgit-core/src/test/groovy/org/ajoberstar/grgit/operation/OpenOpSpec.groovy
I've made the naming of the Credentials parameter consitient between open and clone methods.
=> Consitient parameter naming

grgit-core/src/main/groovy/org/ajoberstar/grgit/Configurable.groovy, grgit-core/src/main/groovy/org/ajoberstar/grgit/internal/AnnotateAtRuntime.java, grgit-core/src/main/groovy/org/ajoberstar/grgit/internal/AnnotateAtRuntimeASTTransformation.java, grgit-core/src/main/groovy/org/ajoberstar/grgit/internal/OpSyntax.groovy, grgit-core/src/main/groovy/org/ajoberstar/grgit/internal/WithOperationsASTTransformation.java
Gradle usage from Groovy build scripts can use the Closure methods
and get a clean delegation:
Grgit.open { currentDir = 'somewhere' }
From Kotlin build scripts, they fell back to the Consumer variant, but
that required the receiver (roughly equivalent in this context to the
Groovy delegate) to be explicitly referenced:
Grgit.open { it.currentDir = 'somewhere' }
Using an interface with @HasImplicitReceiver allows for use like the
above Groovy usage.
Gradle provides the Action interface to meet this need, but in order to
preserve some independence from Gradle's API, since grgit is meant to be
generically a Groovy Git binding, we can't have the Action class or the
HasImplicitReceiver annotation on the classpath during compile.
We're doing a workaround at the moment that adds the annotation …
=> Replace Consumer with HasImplicitReceiver support

grgit-core/src/main/groovy/org/ajoberstar/grgit/util/JGitUtil.groovy
I found the method which still use ```getRef()``` deprecated in JGit.
=> Use findRef() instead of getRef()

grgit-core/src/main/groovy/org/ajoberstar/grgit/CommitDiff.groovy, grgit-core/src/main/groovy/org/ajoberstar/grgit/operation/ShowOp.groovy, grgit-core/src/test/groovy/org/ajoberstar/grgit/operation/ShowOpSpec.groovy
I went for a rather succinct naming - hope that's allright.
Without the explicit null-handling the other ShopOp-testcases failed with an NPE; however I do not know why only for this particular line (maybe a slightly different handling of collectEntries vs. collect?).
=> Added rename tracking to ShowOp (#273).

docs/content/index.adoc
In Maven the property is called `groupId` and not `group` :).
=> Correct POM.xml sample groupId

docs/content/grgit-describe.adoc, grgit-core/src/main/groovy/org/ajoberstar/grgit/operation/DescribeOp.groovy, grgit-core/src/test/groovy/org/ajoberstar/grgit/operation/DescribeOpSpec.groovy
The "always" option is natively supported in JGit 5.4.0 and above.
=> DescribeOp: Add the "always" option

docs/content/grgit-clone.adoc, grgit-core/src/main/groovy/org/ajoberstar/grgit/Grgit.groovy, grgit-core/src/main/groovy/org/ajoberstar/grgit/operation/CloneOp.groovy, grgit-core/src/test/groovy/org/ajoberstar/grgit/operation/CloneOpSpec.groovy
There is probably a nicer way to indicate that `all = false` has no effect unless a list of branches is provided, and to indicate that full refs are required for `CloneOp#branches`, but I think this is a fairly nice match with the underlying Jgit behavior. I made sure that if `all` or `branches` aren't touched then there is no effect on the Jgit `CloneCommand` - the resulting behavior should be the same as without this patch.
=> Closes #145

docs/modules/ROOT/pages/grgit-describe.adoc, grgit-core/src/main/groovy/org/ajoberstar/grgit/operation/DescribeOp.groovy, grgit-core/src/test/groovy/org/ajoberstar/grgit/operation/DescribeOpSpec.groovy
Resolve issue https://github.com/ajoberstar/grgit/issues/254
=> Add support for git describe --abbrev

README.md, grgit-core/src/test/groovy/org/ajoberstar/grgit/operation/LogOpSpec.groovy, grgit-gradle/src/compatTest/groovy/org/ajoberstar/grgit/gradle/GrgitServicePluginCompatTest.groovy, grgit-gradle/src/main/java/org/ajoberstar/grgit/gradle/GrgitServiceExtension.java, grgit-gradle/src/main/java/org/ajoberstar/grgit/gradle/GrgitServicePlugin.java
=> Make the service plugin properly usable (#381)
